from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

CANONICAL_TASKS = (
    "steels",
    "expt_gap",
    "glass",
    "expt_is_metal",
    "jdft2d",
    "dielectric",
    "log_kvrh",
    "log_gvrh",
    "perovskites",
    "phonons",
    "mp_gap",
    "mp_is_metal",
    "mp_e_form",
)

# These are aliases only.  No new indices are generated by Stage2.
SPLIT_ROLE_TO_MANIFEST_ROLE = {
    "train": "holdout_train",
    "val": "holdout_val",
    "test": "outer_test",
}


@dataclass(frozen=True)
class ExpertSpec:
    expert_id: str
    source_task: str
    provider: str
    hidden_dim: int
    export_root: Path
    input_modality: str
    representation_kind: str


@dataclass(frozen=True)
class ExpertPool:
    path: Path
    experts: tuple[ExpertSpec, ...]
    anchor_map: dict[str, str]

    @property
    def expert_ids(self) -> tuple[str, ...]:
        return tuple(value.expert_id for value in self.experts)

    @property
    def hidden_dims(self) -> dict[str, int]:
        return {value.expert_id: value.hidden_dim for value in self.experts}

    def anchor_for(self, task: str) -> str:
        return self.anchor_map[task]


def _mapping(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a mapping")
    return value


def load_expert_pool(path: Path) -> ExpertPool:
    path = path.expanduser().resolve()
    payload = _mapping(yaml.safe_load(path.read_text(encoding="utf-8")), "expert pool")
    if payload.get("schema_version") != "stage1-provider-pool":
        raise ValueError("Expert pool requires the release schema")
    if payload.get("configuration_status") != "release":
        raise ValueError("Expert pool must be marked as a release configuration")
    if payload.get("protocol") != "one_strongest_frozen_expert_per_task":
        raise ValueError("Unexpected expert-pool protocol")
    if payload.get("split_protocol") != "stage1_train_val_test":
        raise ValueError("Expert pool must preserve the Stage-1 split assignment")
    if payload.get("relation_screening") not in {"none", False}:
        raise ValueError("Expert pool must not apply cross-task relation screening")

    raw_experts = payload.get("experts")
    if not isinstance(raw_experts, list) or len(raw_experts) != len(CANONICAL_TASKS):
        raise ValueError("Expert pool requires exactly 13 logical experts")
    experts: list[ExpertSpec] = []
    base = path.parent
    for raw in raw_experts:
        value = _mapping(raw, "expert")
        export_root = Path(str(value["export_root"])).expanduser()
        if not export_root.is_absolute():
            export_root = (base / export_root).resolve()
        spec = ExpertSpec(
            expert_id=str(value["expert_id"]),
            source_task=str(value["source_task"]),
            provider=str(value["provider"]),
            hidden_dim=int(value["hidden_dim"]),
            export_root=export_root,
            input_modality=str(value.get("input_modality", "unknown")),
            representation_kind=str(value.get("representation_kind", "")),
        )
        if spec.source_task not in CANONICAL_TASKS:
            raise ValueError(f"Unknown source task for {spec.expert_id}: {spec.source_task}")
        if spec.hidden_dim < 1:
            raise ValueError(f"Invalid hidden dimension for {spec.expert_id}")
        if spec.representation_kind != "task_trained_hidden":
            raise ValueError(
                f"{spec.expert_id} must export a task-trained hidden representation; "
                "fixed descriptors are not accepted as Stage2 expert hidden states"
            )
        experts.append(spec)
    expert_ids = [value.expert_id for value in experts]
    if len(set(expert_ids)) != len(expert_ids):
        raise ValueError("Logical expert IDs must be unique")
    if set(value.source_task for value in experts) != set(CANONICAL_TASKS):
        raise ValueError("One logical source expert is required for every canonical task")

    anchor_map = {
        str(key): str(value)
        for key, value in _mapping(payload.get("anchor_map"), "anchor_map").items()
    }
    if set(anchor_map) != set(CANONICAL_TASKS):
        raise ValueError("anchor_map must cover exactly the 13 canonical tasks")
    by_id = {value.expert_id: value for value in experts}
    for task, expert_id in anchor_map.items():
        if expert_id not in by_id:
            raise ValueError(f"Anchor {expert_id} for {task} is not in the expert pool")
        if by_id[expert_id].source_task != task:
            raise ValueError(
                f"Anchor {expert_id} is trained for {by_id[expert_id].source_task}, not {task}"
            )
    return ExpertPool(path=path, experts=tuple(experts), anchor_map=anchor_map)
